app:
  logFilterCategories : "EventQueue,Dispath"
  debugLevel:  debug

dbpool:
   default: xyt
   xyt:
      database: "gateway"
      host: "192.168.30.138"
      username: "gw"
      password: "gao123456"
      drive: "mysql"

modules:
#  mqtt:
#      type : inner
#      productKey : a1GvAwy4lNt
#      deviceSecret: ulsuWZkXGzOQsR5L5AYUQpQxLKvidmUi
#      deviceName:  PC1219

  web:
      type : inner
      addr: 0.0.0.0
      port: 88
      publicPath: "./public"
      sotragePath: "./storage"

  debug:
      type : inner