app:
  logFilterCategories : "EventQueue,Dispath"
  debugLevel:  debug

etcdpool:
  default: xyt
  xyt:
    namespace: "gateway"
    host: "${DB_HOST}"
    username: "${DB_USER}"
    password: "${DB_PWD}"

dbpool:
   default: xyt
   xyt:
      database: "gateway"
      host: "${DB_HOST}"
      username: "${DB_USER}"
      password: "${DB_PWD}"
      drive: "mysql"

redispool:
  default: xyt
  xyt:
    database: "gateway"
    host: "${DB_HOST}"
    username: "${DB_USER}"
    password: "${DB_PWD}"
    drive: "${DB_DRIVE}"

modules:
   comment:
     type: inner
     bindAddr: ${COMMENT_ADDR}

#   debug:
#     type: inner
#  mqtt:
#      type : inner
#      productKey : a1GvAwy4lNt
#      deviceSecret: ulsuWZkXGzOQsR5L5AYUQpQxLKvidmUi
#      deviceName:  PC1219

#  web:
#      type : inner
#      addr: 0.0.0.0
#      port: 8080
#      staticFileUrl: "http://127.0.0.1:8080"
#      staticFileVersion : "1001"
#      viewsRoot: "./views"
#      publicRoot: "./public"
#      sotragePath: "./storage"
#      allowOrigins:
#          - "http://127.0.0.1:8080"
#          - "http://localhost:10086"
#          - "http://127.0.0.1:88"


